
SELECT [Amount]
      ,[CloseDate]
      ,[CreatedById]
      ,[CreatedDate]
      ,[CurrencyIsoCode]
      ,[ExpectedRevenue]
      ,[ForecastCategory]
      ,[Id]
      ,[IsDeleted]
      ,[OpportunityId]
      ,[Probability]
      ,[StageName]
      ,[SystemModstamp]
  FROM [SFDCReplicaDB].[dbo].[opportunityhistory]